### ISSUE TITLE
Would be nice if lash just updated the default profile, instead of overwriting the whole credentials file.

### ISSUE THREAD

**Issue by felixmccuaig** [toolsdotgo/lash#122]
Since it only uses the default profile, no need to overwrite the whole thing

**Comment by dtbell91** [comment]
Thanks for the feedback.

Generally, I think anything long lived in your credentials file is probably something to be avoided where possible, that's why `lash` exists to manage accessing roles using short lived tokens generated after authorisation via a user's browser session (backed by whatever SSO they might be using, etc).

If you really want to continue using long lived credentials, the docs have you covered on this. If you put your persistent credentials in either `~/.aws/credentials-head` or `~/.aws/credentials-tail`, `lash` will prepend/append the contents whenever `lash` writes to the `~/.aws/credentials` file.

```
$ lash -h

<... snip ...>

CUSTOM CREDENTIALS
  if you have named, pet creds you need to keep around, use either
  credentials-head or credentials-tail files in the same directory as
  credentials (the aws creds file). they will not be managed and will be
  added to the resulting creds file in a predictable manner.
```

Other than that, the handling of `~/.aws/credentials` is very unlikely to change as it would reduce the friction on using long lived credentials.
